"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { sql } from "@/lib/db";
const schema=z.object({itemId:z.coerce.number().int().positive()});
export async function startTradeFromFinder(formData:FormData){
 const parsed=schema.safeParse({itemId:formData.get("itemId")});
 if(!parsed.success) redirect("/trade-finder?error=invalid-item");
 const itemId=parsed.data.itemId;
 const rows=await sql`with settings as (select account_mode,cash_stack,maximum_capital_percent from app_settings where id=1), latest as (select distinct on(item_id) item_id,latest_low,latest_high,latest_low_time,latest_high_time,coalesce(high_volume_5m,0)+coalesce(low_volume_5m,0) volume_5m,coalesce(high_volume_1h,0)+coalesce(low_volume_1h,0) volume_1h from market_snapshots where item_id=${itemId} order by item_id,observed_at desc), portfolio as (select coalesce(sum(capital_committed),0) committed from trades where status not in ('COMPLETED','CANCELLED')), free_slot as (select n slot_number from generate_series(1,case when (select account_mode from settings)='F2P' then 3 else 8 end) n where not exists(select 1 from trades where slot_number=n and status not in ('COMPLETED','CANCELLED')) order by n limit 1), candidate as (select items.id item_id,items.name,latest_low buy_price,latest_high sell_price,greatest(0,latest_high-least(5000000,floor(latest_high*0.02))-latest_low) profit_each,least(coalesce(items.buy_limit,1),greatest(1,floor(least(settings.cash_stack-portfolio.committed,settings.cash_stack*settings.maximum_capital_percent/100)/latest_low)::integer),greatest(1,least(coalesce(nullif(volume_5m,0),1),greatest(1,floor(volume_1h/12)::integer)))) quantity,free_slot.slot_number from latest join items on items.id=latest.item_id cross join settings cross join portfolio cross join free_slot where latest_low>0 and latest_high>latest_low and latest_low_time>=now()-interval '24 hours' and latest_high_time>=now()-interval '24 hours' and (settings.account_mode='P2P' or items.members=false) and settings.cash_stack-portfolio.committed>=latest_low), inserted as (insert into trades(item_id,slot_number,status,planned_quantity,suggested_buy_price,suggested_sell_price,capital_committed,expected_profit,expected_roi,current_instruction) select item_id,slot_number,'BUY_READY',quantity,buy_price,sell_price,buy_price*quantity,profit_each*quantity,profit_each::numeric/buy_price,'Place a buy offer for '||quantity||' '||name||' at '||buy_price||' GP each.' from candidate where profit_each>0 returning id) insert into trade_events(trade_id,event_type,new_status,note,system_generated) select id,'TRADE_STARTED','BUY_READY','Created from Trade Finder after a fresh server-side check.',true from inserted returning trade_id`;
 if(rows.length===0) redirect("/trade-finder?error=could-not-start");
 revalidatePath("/");revalidatePath("/trade-finder");revalidatePath("/trades");redirect("/trades?started=1");
}
