function finite(value, fallback) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
function iso(ms) { return new Date(ms).toISOString(); }
function summarizeItems(trades, openPositions) {
  const map = new Map();
  for (const t of trades) { const k=String(t.itemId); const x=map.get(k)??{itemId:k,itemName:t.itemName,completedTrades:0,wins:0,realizedPnl:0,fees:0,openPositions:0,unrealizedPnl:0}; x.completedTrades++; x.wins+=t.pnl>0?1:0; x.realizedPnl+=t.pnl; x.fees+=t.entryFee+t.exitFee; map.set(k,x); }
  for (const p of openPositions) { const k=String(p.itemId); const x=map.get(k)??{itemId:k,itemName:p.itemName,completedTrades:0,wins:0,realizedPnl:0,fees:0,openPositions:0,unrealizedPnl:0}; x.openPositions++; x.unrealizedPnl+=p.unrealizedPnl; x.fees+=p.entryFee; map.set(k,x); }
  return [...map.values()].map(x=>({...x,winRate:x.completedTrades?x.wins/x.completedTrades:null,totalPnl:x.realizedPnl+x.unrealizedPnl})).sort((a,b)=>a.totalPnl-b.totalPnl);
}
export function simulate(rows, options={}) {
  const startingCash=finite(options.startingCash,1e7), allocation=finite(options.allocation,.1), maxPositions=Math.max(1,Math.floor(finite(options.maxPositions,3))), holdMs=finite(options.holdMinutes,240)*60000, threshold=finite(options.threshold,.005), costRate=finite(options.costBps,20)/10000, slipRate=finite(options.slippageBps,10)/10000, cooldownMs=finite(options.cooldownMinutes,240)*60000, minCompletedTrades=Math.max(0,Math.floor(finite(options.minCompletedTrades,30))), forceLiquidation=Boolean(options.forceLiquidation), predictor=options.predictor??(r=>Number(r.momentum_60m));
  const clean=[...rows].filter(r=>Number.isFinite(Date.parse(r.bucket_at))&&finite(r.midpoint,0)>0).sort((a,b)=>Date.parse(a.bucket_at)-Date.parse(b.bucket_at)||String(a.item_id).localeCompare(String(b.item_id)));
  const groups=new Map(); for(const row of clean){const t=Date.parse(row.bucket_at);if(!groups.has(t))groups.set(t,[]);groups.get(t).push(row)}
  const timestamps=[...groups.keys()], firstAt=timestamps[0]??null, lastAt=timestamps.at(-1)??null, spanMinutes=firstAt==null?0:(lastAt-firstAt)/60000;
  let cash=startingCash,peak=startingCash,maxDrawdown=0,realizedPnl=0,entryFees=0,exitFees=0,notionalTime=0,lastCurveAt=null;
  const positions=new Map(), cooldown=new Map(), trades=[], equityCurve=[];
  const close=(id,p,time,rawExit,reason)=>{const exitPrice=rawExit*(1-slipRate),proceeds=p.quantity*exitPrice,exitFee=proceeds*costRate,pnl=proceeds-exitFee-p.totalCost;cash+=proceeds-exitFee;realizedPnl+=pnl;exitFees+=exitFee;trades.push({itemId:id,itemName:p.itemName,entryAt:iso(p.entryAt),exitAt:iso(time),entryPrice:p.entryPrice,exitPrice,quantity:p.quantity,entryFee:p.entryFee,exitFee,totalFees:p.entryFee+exitFee,pnl,returnPct:pnl/p.totalCost,reason});positions.delete(id);cooldown.set(id,time+cooldownMs)};
  for(const [time,bucket] of groups){
    if(lastCurveAt!=null){const deployed=[...positions.values()].reduce((s,p)=>s+p.totalCost,0);notionalTime+=deployed*(time-lastCurveAt)} lastCurveAt=time;
    const prices=new Map(bucket.map(r=>[String(r.item_id),finite(r.midpoint,0)]));
    for(const [id,p] of [...positions]) if(time>=p.exitAt&&prices.has(id)) close(id,p,time,prices.get(id),'time_exit');
    const candidates=bucket.map(row=>({row,score:Number(predictor(row))})).filter(x=>Number.isFinite(x.score)&&x.score>=threshold).sort((a,b)=>b.score-a.score||String(a.row.item_id).localeCompare(String(b.row.item_id)));
    for(const {row,score} of candidates){if(positions.size>=maxPositions)break;const id=String(row.item_id);if(positions.has(id)||time<(cooldown.get(id)??0))continue;const entryPrice=finite(row.midpoint,0)*(1+slipRate),budget=Math.min(cash,startingCash*allocation),quantity=Math.floor(budget/(entryPrice*(1+costRate)));if(quantity<1)continue;const principal=quantity*entryPrice,entryFee=principal*costRate,totalCost=principal+entryFee;if(totalCost>cash)continue;cash-=totalCost;entryFees+=entryFee;positions.set(id,{itemId:id,itemName:row.item_name,entryAt:time,exitAt:time+holdMs,entryPrice,quantity,entryFee,totalCost,score,lastRawPrice:finite(row.midpoint,0),lastAt:time});}
    for(const [id,p] of positions) if(prices.has(id)){p.lastRawPrice=prices.get(id);p.lastAt=time}
    let equity=cash;for(const p of positions.values())equity+=p.quantity*p.lastRawPrice;peak=Math.max(peak,equity);maxDrawdown=Math.max(maxDrawdown,peak?((peak-equity)/peak):0);equityCurve.push({at:iso(time),equity,cash,deployedCapital:equity-cash,capitalUtilization:startingCash?(equity-cash)/startingCash:0,openPositions:positions.size});
  }
  if(forceLiquidation&&lastAt!=null){for(const [id,p] of [...positions])close(id,p,lastAt,p.lastRawPrice,'end_of_period');let equity=cash;peak=Math.max(peak,equity);maxDrawdown=Math.max(maxDrawdown,peak?((peak-equity)/peak):0);equityCurve.push({at:iso(lastAt),equity,cash,deployedCapital:0,capitalUtilization:0,openPositions:0});}
  const openPositions=[...positions.values()].map(p=>{const markPrice=p.lastRawPrice,markValue=p.quantity*markPrice,unrealizedPnl=markValue-p.totalCost;return{itemId:p.itemId,itemName:p.itemName,entryAt:iso(p.entryAt),scheduledExitAt:iso(p.exitAt),lastMarkedAt:iso(p.lastAt),entryPrice:p.entryPrice,markPrice,quantity:p.quantity,entryFee:p.entryFee,totalCost:p.totalCost,markValue,unrealizedPnl,returnPct:unrealizedPnl/p.totalCost,score:p.score}});
  const finalEquity=equityCurve.at(-1)?.equity??cash,wins=trades.filter(t=>t.pnl>0).length,avgUtil=spanMinutes>0?notionalTime/(startingCash*(lastAt-firstAt)):0;
  const warnings=[];if(spanMinutes<options.holdMinutes)warnings.push(`Evaluation span (${spanMinutes.toFixed(1)}m) is shorter than hold period (${finite(options.holdMinutes,240)}m).`);if(trades.length<minCompletedTrades)warnings.push(`Only ${trades.length} completed trades; minimum diagnostic target is ${minCompletedTrades}.`);if(openPositions.length)warnings.push(`${openPositions.length} positions remain open and are marked to the latest midpoint.`);
  return{summary:{startingCash,finalEquity,totalReturnPct:startingCash?(finalEquity-startingCash)/startingCash:0,realizedPnl,unrealizedPnl:openPositions.reduce((s,p)=>s+p.unrealizedPnl,0),trades:trades.length,winRate:trades.length?wins/trades.length:null,maxDrawdown,openPositions:openPositions.length,entryFees,exitFees,totalFees:entryFees+exitFees,averageCapitalUtilization:avgUtil,evaluationSpanMinutes:spanMinutes,holdMinutes:finite(options.holdMinutes,240),statisticallyUsable:trades.length>=minCompletedTrades&&spanMinutes>=finite(options.holdMinutes,240)},warnings,trades,openPositions,itemAttribution:summarizeItems(trades,openPositions),equityCurve};
}
